/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    /** Root */
    get: operations["root__get"]
  }
  "/meetings/list": {
    /** Get Meetings List */
    get: operations["get_meetings_list_meetings_list_get"]
  }
  "/meetings/next": {
    /** Get Next Meeting */
    get: operations["get_next_meeting_meetings_next_get"]
  }
  "/meetings/current": {
    /** Get Current Meeting */
    get: operations["get_current_meeting_meetings_current_get"]
  }
  "/lab/hours/today": {
    /** Get Hours Today */
    get: operations["get_hours_today_lab_hours_today_get"]
  }
  "/lab/hours/{date}": {
    /** Get Hours Date */
    get: operations["get_hours_date_lab_hours__date__get"]
  }
  "/lab/num_users": {
    /** Get Num Users In Lab */
    get: operations["get_num_users_in_lab_lab_num_users_get"]
  }
  "/lab/staff": {
    /** Get Staff In Lab */
    get: operations["get_staff_in_lab_lab_staff_get"]
  }
  "/lab/desktops": {
    /** Desktop Usage */
    get: operations["desktop_usage_lab_desktops_get"]
  }
  "/session/log": {
    /**
     * Log Session
     * @description Primary API endpoint for session tracking.
     *
     * Desktops have a cronjob that calls this endpoint: https://git.io/vpIKX
     */
    post: operations["log_session_session_log_post"]
  }
  "/shorturls/bounce/{slug}": {
    /** Bounce Shorturl */
    get: operations["bounce_shorturl_shorturls_bounce__slug__get"]
  }
  "/auth/calnet": {
    /** Calnet Login */
    get: operations["calnet_login_auth_calnet_get"]
  }
  "/auth/calnet/callback": {
    /** Calnet Login Callback */
    get: operations["calnet_login_callback_auth_calnet_callback_get"]
  }
  "/account/reset_password": {
    /** Reset Password */
    post: operations["reset_password_account_reset_password_post"]
  }
  "/account/command": {
    /** Run Command */
    post: operations["run_command_account_command_post"]
  }
  "/account/me": {
    /** Get Account Info */
    get: operations["get_account_info_account_me_get"]
  }
  "/account/quota/paper": {
    /** Get Paper Quota */
    get: operations["get_paper_quota_account_quota_paper_get"]
    /** Add Paper Refund */
    post: operations["add_paper_refund_account_quota_paper_post"]
  }
  "/account/hosting/vhost": {
    /** Request Vhost */
    post: operations["request_vhost_account_hosting_vhost_post"]
  }
  "/account/hosting/mail": {
    /** Get Vhost Mail */
    get: operations["get_vhost_mail_account_hosting_mail_get"]
    /** Vhost Mail Update */
    post: operations["vhost_mail_update_account_hosting_mail_post"]
  }
  "/account/hosting/mail/export": {
    /** Vhost Mail Csv Export */
    get: operations["vhost_mail_csv_export_account_hosting_mail_export_get"]
  }
  "/account/hosting/mail/import": {
    /** Vhost Mail Csv Import */
    post: operations["vhost_mail_csv_import_account_hosting_mail_import_post"]
  }
  "/account/register": {
    /** Register Account */
    post: operations["register_account_account_register_post"]
  }
  "/account/register/status": {
    /** Register Account Status */
    get: operations["register_account_status_account_register_status_get"]
  }
  "/announce/blog": {
    /** Get Blog Posts */
    get: operations["get_blog_posts_announce_blog_get"]
  }
  "/staff_hours": {
    /** Get Staff Hours */
    get: operations["get_staff_hours_staff_hours_get"]
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    /** AccountInfoOutput */
    AccountInfoOutput: {
      /** Username */
      username: string
      /** Email */
      email: string
      /** Name */
      name: string
      /**
       * Type
       * @enum {string}
       */
      type: "personal" | "group"
      /** Groups */
      groups: string[]
    }
    /** Body_vhost_mail_csv_import_account_hosting_mail_import_post */
    Body_vhost_mail_csv_import_account_hosting_mail_import_post: {
      data: components["schemas"]["VHostMailImportInput"]
      /**
       * Csv File
       * Format: binary
       */
      csv_file?: string
    }
    /** DesktopUsageOutput */
    DesktopUsageOutput: {
      /** All Desktops In Use */
      all_desktops_in_use: string[]
      /** All Desktops Num */
      all_desktops_num: number
      /** Public Desktops In Use */
      public_desktops_in_use: string[]
      /** Public Desktops Num */
      public_desktops_num: number
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][]
    }
    /** HoursOutput */
    HoursOutput: {
      /** Open */
      open?: string
      /** Close */
      close?: string
    }
    /** LogSessionInput */
    LogSessionInput: {
      state: components["schemas"]["SessionState"]
      /** User */
      user?: string
    }
    /** MailVHost */
    MailVHost: {
      /** Domain */
      domain: string
      /** Addresses */
      addresses: string[]
      /** Has Wildcard */
      has_wildcard: boolean
    }
    /** MeetingOutput */
    MeetingOutput: {
      /** Day */
      day: string
      /** Time */
      time: string
      /** Subject */
      subject: string
      /** Short */
      short: string
      /** Irl */
      irl: boolean
      /** Virtual */
      virtual: boolean
    }
    /** MeetingsListOutput */
    MeetingsListOutput: {
      /** Meetings */
      meetings: components["schemas"]["MeetingOutput"][]
    }
    /** NumUsersOutput */
    NumUsersOutput: {
      /** Num Users */
      num_users: number
    }
    /** PaperQuotaOutput */
    PaperQuotaOutput: {
      /** User */
      user: string
      /** Daily */
      daily: number
      /** Semesterly */
      semesterly: number
    }
    /** PaperRefundInput */
    PaperRefundInput: {
      /** Username */
      username: string
      /** Pages */
      pages: number
      /** Reason */
      reason: string
    }
    /** RegisterAccountError */
    RegisterAccountError: {
      /** State */
      state: string
      /** Account */
      account: string
      /** Calnet Uid */
      calnet_uid: string
    }
    /** RegisterAccountInput */
    RegisterAccountInput: {
      /**
       * Account Association
       * @description CalNet UID/CalLink OID of entity to create account for
       */
      account_association: number
      /** Username */
      username: string
      /** Password */
      password: string
      /** Contact Email */
      contact_email: string
    }
    /** RegisterAccountOutput */
    RegisterAccountOutput: {
      /** Status */
      status: string
      /** Task Id */
      task_id: string
    }
    /** RegisterAccountStatusOutput */
    RegisterAccountStatusOutput: {
      /** State */
      state: string
      /** Status */
      status?: string[]
      /** Message */
      message?: string
    }
    /** ResetPasswordInput */
    ResetPasswordInput: {
      /** Account */
      account: string
      /** New Password */
      new_password: string
    }
    /** RunCommandInput */
    RunCommandInput: {
      /** Command */
      command: string
      /** Username */
      username: string
      /** Password */
      password: string
    }
    /** RunCommandOutput */
    RunCommandOutput: {
      /** Output */
      output: string
      /** Error */
      error: string
    }
    /**
     * SessionState
     * @description An enumeration.
     * @enum {string}
     */
    SessionState: "active" | "cleanup"
    /** StaffHour */
    StaffHour: {
      /** Day */
      day: string
      /** Time */
      time: string
      /** Staff */
      staff: components["schemas"]["StaffHourStaff"][]
      /** Cancelled */
      cancelled: boolean
    }
    /** StaffHourStaff */
    StaffHourStaff: {
      /** User Name */
      user_name: string
      /** Real Name */
      real_name: string
      /** Position */
      position: string
    }
    /** StaffHoursOutput */
    StaffHoursOutput: {
      /** Staff Hours */
      staff_hours: components["schemas"]["StaffHour"][]
    }
    /** StaffInLabOutput */
    StaffInLabOutput: {
      /** Staff In Lab */
      staff_in_lab: components["schemas"]["StaffSession"][]
    }
    /** StaffSession */
    StaffSession: {
      /** User */
      user: string
      /** Host */
      host: string
      /**
       * Start
       * Format: date-time
       */
      start: string
      /**
       * End
       * Format: date-time
       */
      end?: string
    }
    /** VHostMailExportInput */
    VHostMailExportInput: {
      /** Domain */
      domain: string
    }
    /** VHostMailImportInput */
    VHostMailImportInput: {
      /** Domain */
      domain: string
    }
    /** VHostMailOutput */
    VHostMailOutput: {
      /** Vhosts */
      vhosts: components["schemas"]["MailVHost"][]
    }
    /** VHostMailUpdateInput */
    VHostMailUpdateInput: {
      /**
       * Action
       * @enum {string}
       */
      action: "add" | "update" | "delete"
      /** Addr */
      addr: string
      /** Forward To */
      forward_to?: string
      /** Password */
      password?: string
      /** New Addr */
      new_addr?: string
    }
    /** VHostRequestInput */
    VHostRequestInput: {
      /** Subdomain */
      subdomain: string
      /** Name */
      name: string
      /** Email */
      email: string
      /** Position */
      position: string
      /** Comments */
      comments?: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type external = Record<string, never>

export interface operations {
  root__get: {
    /** Root */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>
        }
      }
    }
  }
  get_meetings_list_meetings_list_get: {
    /** Get Meetings List */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MeetingsListOutput"]
        }
      }
    }
  }
  get_next_meeting_meetings_next_get: {
    /** Get Next Meeting */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MeetingOutput"]
        }
      }
    }
  }
  get_current_meeting_meetings_current_get: {
    /** Get Current Meeting */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MeetingOutput"]
        }
      }
    }
  }
  get_hours_today_lab_hours_today_get: {
    /** Get Hours Today */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HoursOutput"]
        }
      }
    }
  }
  get_hours_date_lab_hours__date__get: {
    /** Get Hours Date */
    parameters: {
      path: {
        date: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HoursOutput"]
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_num_users_in_lab_lab_num_users_get: {
    /** Get Num Users In Lab */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["NumUsersOutput"]
        }
      }
    }
  }
  get_staff_in_lab_lab_staff_get: {
    /** Get Staff In Lab */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["StaffInLabOutput"]
        }
      }
    }
  }
  desktop_usage_lab_desktops_get: {
    /** Desktop Usage */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DesktopUsageOutput"]
        }
      }
    }
  }
  log_session_session_log_post: {
    /**
     * Log Session
     * @description Primary API endpoint for session tracking.
     *
     * Desktops have a cronjob that calls this endpoint: https://git.io/vpIKX
     */
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogSessionInput"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: never
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  bounce_shorturl_shorturls_bounce__slug__get: {
    /** Bounce Shorturl */
    parameters: {
      path: {
        slug: string
      }
    }
    responses: {
      /** @description Successful Response */
      308: {
        content: {
          "application/json": Record<string, never>
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  calnet_login_auth_calnet_get: {
    /** Calnet Login */
    parameters: {
      query?: {
        next?: string
      }
      header: {
        host: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  calnet_login_callback_auth_calnet_callback_get: {
    /** Calnet Login Callback */
    parameters: {
      query: {
        ticket: string
      }
      header?: {
        host?: string
      }
      cookie?: {
        calnet_redirect_url?: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  reset_password_account_reset_password_post: {
    /** Reset Password */
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordInput"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: never
      /** @description Bad Request */
      400: never
      /** @description Forbidden */
      403: never
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
      /** @description Internal Server Error */
      500: never
    }
  }
  run_command_account_command_post: {
    /** Run Command */
    requestBody: {
      content: {
        "application/json": components["schemas"]["RunCommandInput"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RunCommandOutput"]
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_account_info_account_me_get: {
    /** Get Account Info */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AccountInfoOutput"]
        }
      }
    }
  }
  get_paper_quota_account_quota_paper_get: {
    /** Get Paper Quota */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PaperQuotaOutput"]
        }
      }
    }
  }
  add_paper_refund_account_quota_paper_post: {
    /** Add Paper Refund */
    requestBody: {
      content: {
        "application/json": components["schemas"]["PaperRefundInput"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: never
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  request_vhost_account_hosting_vhost_post: {
    /** Request Vhost */
    requestBody: {
      content: {
        "application/json": components["schemas"]["VHostRequestInput"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: never
      /** @description Bad Request */
      400: never
      /** @description Forbidden */
      403: never
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
      /** @description Internal Server Error */
      500: never
    }
  }
  get_vhost_mail_account_hosting_mail_get: {
    /** Get Vhost Mail */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["VHostMailOutput"]
        }
      }
    }
  }
  vhost_mail_update_account_hosting_mail_post: {
    /** Vhost Mail Update */
    requestBody: {
      content: {
        "application/json": components["schemas"]["VHostMailUpdateInput"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: never
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  vhost_mail_csv_export_account_hosting_mail_export_get: {
    /** Vhost Mail Csv Export */
    requestBody: {
      content: {
        "application/json": components["schemas"]["VHostMailExportInput"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  vhost_mail_csv_import_account_hosting_mail_import_post: {
    /** Vhost Mail Csv Import */
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_vhost_mail_csv_import_account_hosting_mail_import_post"]
      }
    }
    responses: {
      /** @description Successful Response */
      204: never
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  register_account_account_register_post: {
    /** Register Account */
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterAccountInput"]
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RegisterAccountOutput"]
        }
      }
      /** @description Forbidden */
      403: {
        content: {
          "application/json": components["schemas"]["RegisterAccountError"]
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  register_account_status_account_register_status_get: {
    /** Register Account Status */
    parameters: {
      query: {
        task_id: string
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RegisterAccountStatusOutput"]
        }
      }
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"]
        }
      }
    }
  }
  get_blog_posts_announce_blog_get: {
    /** Get Blog Posts */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>
        }
      }
    }
  }
  get_staff_hours_staff_hours_get: {
    /** Get Staff Hours */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["StaffHoursOutput"]
        }
      }
    }
  }
}
