name: CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [16]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      # https://github.com/actions/cache/blob/v3.0.11/examples.md#node---yarn-2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Check yarn lockfile
        run: |
          yarn dedupe --check
      - name: Install dependencies
        run: |
          yarn install --immutable
      - name: Check formatting
        run: |
          yarn prettier --check .
      - name: Typecheck
        run: |
          yarn typecheck
      - name: Lint
        run: |
          yarn lint --max-warnings=0
