name: CI
on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      # https://github.com/actions/cache/blob/v3.0.11/examples.md#node---yarn-2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install --immutable
      - name: Check formatting
        run: |
          yarn prettier --check .
      - name: Typecheck
        run: |
          yarn typecheck
      - name: Lint
        run: |
          yarn lint --max-warnings=0

  transpire-ci:
    uses: ocf/transpire-ci/.github/workflows/trigger.yml@master
    needs: lint
    if: success() && github.ref == 'refs/heads/master'
    with:
      module_name: ocfstatic
    secrets:
      TRANSPIRE_CI_PAT: ${{ secrets.TRANSPIRE_CI_PAT }}
